### ISSUE TITLE
add release for TBCC

### ISSUE THREAD

**Issue by dels78** [StephenSwat/adibags-better-categories#1]
Love this addon and the categories seem to be working still with TBCC but it shows as no release available for it in the update clients (like WoWup)

**Comment by stephenswat** [comment]
Version 0.3.1 for The Burning Crusade Classic is now available from the repository or from CurseForge. The game itself has far better item categorization in Burning Crusade, so there is less need for this addon, but I will be on the lookout for cases where the game fails to categorize things properly and add them to this addon.
